### ISSUE TITLE
Feature List for Release

### ISSUE THREAD

**Issue by justinhough** [justinhough/postcss-shopify-theme-starter#1]
## TODOS
- [ ] sync with Shopify DEV store
- [ ] add basic layout and snippets for basic page / component structure
- [ ] include locales (languages) for de, en, es, fr, pt-BR, and pt-PT
- [ ] build templates for:
  - [ ] home
  - [ ] article
  - [ ] blog
  - [ ] cart
  - [ ] collection
  - [ ] collection list
  - [ ] gift card
  - [ ] contact
  - [ ] page
  - [ ] product
  - [ ] search
  - [ ] customer - account
  - [ ] customer - activate account
  - [ ] customer - addresses
  - [ ] customer - login
  - [ ] customer - order
  - [ ] customer - register
  - [ ] customer - reset password
  - [ ] 404
- [ ] basic theme testing
